### ISSUE TITLE
Spiegelung

### ISSUE THREAD

**Issue by MartinThoma** [MartinThoma/ml-abschlusspaper#1]
Da wir Probleme mit Spiegelungen hatten könnte man eventuell das erwähnen:

https://www.googlewatchblog.de/2015/08/google-forscher-algorithmus-entfernung/

**Comment by VitaliKaiser** [comment]
stimmt das paper war ziemlich cool. Werde es mal erwähnen :)

**Comment by MartinThoma** [comment]
Zu spät
