### ISSUE TITLE
subproblem / sub problem

### ISSUE THREAD

**Issue by MartinThoma** [MartinThoma/ml-abschlusspaper#12]
I think it should be "subproblem", not "sub problem" (see https://books.google.com/ngrams/graph?content=sub+problem%2Csubproblem&case_insensitive=on&year_start=1800&year_end=2000&corpus=15&smoothing=3&share=&direct_url=t1%3B%2Csub%20problem%3B%2Cc0%3B.t4%3B%2Csubproblem%3B%2Cc0%3B%2Cs0%3B%3Bsubproblem%3B%2Cc0%3B%3BSubproblem%3B%2Cc0%3B%3BSUBPROBLEM%3B%2Cc0)

**Comment by VitaliKaiser** [comment]
check
