### ISSUE TITLE
cref

### ISSUE THREAD

**Issue by MartinThoma** [MartinThoma/ml-abschlusspaper#14]
I suggest we should always use `\cref` (from https://www.ctan.org/pkg/cleveref) instead of `\ref`. This adds "section", "equation", "table" or whatever automatically and links this word + the number.

@VitaliKaiser `grep -rnI "\\\\ref" *` -> bei dir sind noch zwei `\ref`

**Comment by VitaliKaiser** [comment]
check: ch2 angepasst
Sollen wir damit das Issue schließen?

**Comment by MartinThoma** [comment]
Ja, ich glaube jeder hat es gesehen und überall passt es (glaube ich).

**Comment by MartinThoma** [comment]
@VitaliKaiser Wobei es schön ist, wenn man so was in der commit message macht (mit "fixes #xy")
