### ISSUE TITLE
Classification Net

### ISSUE THREAD

**Issue by MartinThoma** [MartinThoma/ml-abschlusspaper#16]
I would rather speak of "models" (e.g. in the caption of Table I: "Topology of our Classification Net" I would rather write "Topology of our model")

(We should also try not to write "our")

**Comment by MarvinTeichmann** [comment]
I feel that model does not really fit into that caption. For me the model is a much more general concept, where the neuronal network is part of the model. The model itself does not have a topology.

**Comment by MartinThoma** [comment]
I'd say a neural network is one way to model the "real" function which maps the data (input vector) to the class (output vector).
