### ISSUE TITLE
Pixel which are close to each other...

### ISSUE THREAD

**Issue by MartinThoma** [MartinThoma/ml-abschlusspaper#19]
> However it is not useful to actually use all of this data. Pixel which are close to each other deliver a very similar input as their is a high intersect in the corresponding input section.

sounds a bit cumbersome to me. It should probably rather be

> However, it is not useful to actually use all of this data as patches which are close to each other are very similar.

Directly after that:

> Hence the information gain of including this inputs are very small.

should be

> Hence the information gain of including these patches is very small.

**Comment by MartinThoma** [comment]
And:

> If we set the stride to s the center pixel selected for data generation have a distance of s in each dimension to its nearest neighbour.

should be something like

> A stride of s results in the center pixels having a distance of s in height and with to the next patches center pixel. This is important in the patch generation step before training as well as for the pixel-wise classification.

**Comment by MarvinTeichmann** [comment]
fixed.
