### ISSUE TITLE
mega-pixel

### ISSUE THREAD

**Issue by MartinThoma** [MartinThoma/ml-abschlusspaper#20]
Should be "megapixel". See 
- https://en.wikipedia.org/wiki/Pixel#Megapixel
- https://books.google.com/ngrams/graph?content=mega-pixel%2C+megapixel&case_insensitive=on&year_start=1800&year_end=2000&corpus=15&smoothing=3&share=&direct_url=t4%3B%2Cmega%20-%20pixel%3B%2Cc0%3B%2Cs0%3B%3Bmega%20-%20pixel%3B%2Cc0%3B%3BMega%20-%20pixel%3B%2Cc0%3B.t4%3B%2Cmegapixel%3B%2Cc0%3B%2Cs0%3B%3Bmegapixel%3B%2Cc0%3B%3BMegapixel%3B%2Cc0%3B%3BMegaPixel%3B%2Cc0%3B%3BMEGAPIXEL%3B%2Cc0

**Comment by MarvinTeichmann** [comment]
fixed.
