### ISSUE TITLE
Plural of pixel is pixels, not pixel

### ISSUE THREAD

**Issue by MartinThoma** [MartinThoma/ml-abschlusspaper#21]
See https://en.wiktionary.org/wiki/pixel#Noun

e.g.:

> we skip s-1 pixel in each dimension

(also: `$s-1$`, not `s-1`)

and

> Figure 4 shows the result of the sliding window approach with a stride of 10.

should be

> Figure 4 shows the result of the sliding window approach with a stride of $s=10$.

**Comment by MarvinTeichmann** [comment]
fixed.
