### ISSUE TITLE
neural network, not neuronal network

### ISSUE THREAD

**Issue by MartinThoma** [MartinThoma/ml-abschlusspaper#22]
see
- https://en.wikipedia.org/wiki/Artificial_neural_network
- https://books.google.com/ngrams/graph?content=neural+network%2C+neuronal+network&case_insensitive=on&year_start=1800&year_end=2000&corpus=15&smoothing=3&share=&direct_url=t4%3B%2Cneural%20network%3B%2Cc0%3B%2Cs0%3B%3Bneural%20network%3B%2Cc0%3B%3BNeural%20Network%3B%2Cc0%3B%3BNeural%20network%3B%2Cc0%3B%3BNEURAL%20NETWORK%3B%2Cc0%3B.t4%3B%2Cneuronal%20network%3B%2Cc0%3B%2Cs0%3B%3Bneuronal%20network%3B%2Cc0%3B%3BNeuronal%20network%3B%2Cc0%3B%3BNeuronal%20Network%3B%2Cc0

**Comment by VitaliKaiser** [comment]
check: ch2 keine vorkommnisse

**Comment by MarvinTeichmann** [comment]
fixed.
