### ISSUE TITLE
dataset -> data set

### ISSUE THREAD

**Issue by MartinThoma** [MartinThoma/ml-abschlusspaper#24]
"Data set" seems to be more commonly used than "dataset":
- https://books.google.com/ngrams/graph?content=dataset%2C+data+set&case_insensitive=on&year_start=1800&year_end=2000&corpus=15&smoothing=3&share=&direct_url=t4%3B%2Cdataset%3B%2Cc0%3B%2Cs0%3B%3Bdataset%3B%2Cc0%3B%3BDataset%3B%2Cc0%3B%3BDATASET%3B%2Cc0%3B%3BDataSet%3B%2Cc0%3B.t4%3B%2Cdata%20set%3B%2Cc0%3B%2Cs0%3B%3Bdata%20set%3B%2Cc0%3B%3BData%20Set%3B%2Cc0%3B%3BDATA%20SET%3B%2Cc0%3B%3BData%20set%3B%2Cc0
- https://en.wikipedia.org/wiki/Data_set

**Comment by VitaliKaiser** [comment]
check: in ch2 angepasst
