### ISSUE TITLE
Content in Related Work

### ISSUE THREAD

**Issue by MarvinTeichmann** [MartinThoma/ml-abschlusspaper#25]
Please add Content to:

```
\subsection{CNN}
A CNN is bla.

\subsection{FCN}
Is CNN where bla.
```

@VitaliKaiser

**Comment by VitaliKaiser** [comment]
Bin heute schon etwas zu müde um nicht total schreckliche Texte zu schreiben, werde ich aber nachholen.... werde für das FZI ein Vermerk machen das da noch etwas Inhalt hinkommt.
