### ISSUE TITLE
GPU immer gross schreiben

### ISSUE THREAD

**Issue by VitaliKaiser** [MartinThoma/ml-abschlusspaper#27]
Ich würde GPU immer groß schreiben

Gegenbeispiel in ch6:
"For n we used 51. This constant was choosen as we ran into
gpu memory"
@mtmann

**Comment by MartinThoma** [comment]
fixed with https://github.com/MartinThoma/ml-abschlusspaper/commit/5ef33fa40bacb98b32bbd6d900d229f9342425fe
