### ISSUE TITLE
51^2 output filter

### ISSUE THREAD

**Issue by MartinThoma** [MartinThoma/ml-abschlusspaper#28]
@mtmann Why is the output filter denoted with 51^2 while all others are denoted as 51 x 51? Is something different happening there?

**Comment by MarvinTeichmann** [comment]
The output is flattened. The shape is (2601,1) while all the other layer have an output of shape (51,51).

**Comment by MartinThoma** [comment]
I would rather write `$2601 \times 1$` there and adjust the caption:

``` tex
Topology of the regression network. The output is a flattened image patch of the size $51^2$.
```

**Comment by MarvinTeichmann** [comment]
I had thought about writing `$2601 \times 1$` . The disadvantage is that people might wonder where 2601 comes from. Do you think that `$51^2 \times 1$` is really that confusing? The  '\times 1$`indicates that`$51^2 \times 1$`is not the same as`$51 \times 51$ `

Well I do not believe that the shape of the output belongs in the caption. The overall purpose of the Table is to describe layers and their shape.  The output shape is not an important information and it can be found in the table.

**Comment by MartinThoma** [comment]
I would rather write 2601. I wondered what `51^2` is supposed to mean. But you should somewhere state that `51^2 = 2601`. And I would do so in the table caption as this is the place where the number occurs.

**Comment by MartinThoma** [comment]
Fixed by https://github.com/MartinThoma/ml-abschlusspaper/commit/96f28464cd37814d8382780594e1630a3850bac4

**Comment by MartinThoma** [comment]
@mtmann What do you think about expanding the footnote to "The shape of $2601 \times 1$ is a result of flattening the $51 \times 51$ image patch. This is only necessary due to tooling support." or something similar. I would also change the footnote symbol "1" to a symbol (see http://tex.stackexchange.com/a/829/5645) as it makes it more clear that it is actually a footnote and not something of the equation.
