### ISSUE TITLE
discredited

### ISSUE THREAD

**Issue by MartinThoma** [MartinThoma/ml-abschlusspaper#35]
> Traditionally neural networks are used for classification tasks and as discredited in the introduction they deliver impressive results.

What? Did you really want to write "discredited"? Where is that in the introduction?

**Comment by MarvinTeichmann** [comment]
Changed. Do you agree with the new statement?

**Comment by MartinThoma** [comment]
@mtmann I don't know. Please commit your changes, reference this issue in the commit message and push them.

**Comment by MartinThoma** [comment]
Fixed by https://github.com/MartinThoma/ml-abschlusspaper/commit/8c55a66a9546c09e5fcf90d7cefa99d4c1f09c0b
