### ISSUE TITLE
Bildquellen

### ISSUE THREAD

**Issue by MartinThoma** [MartinThoma/ml-abschlusspaper#9]
Bildquellen müssen angegeben werden
@VitaliKaiser

**Comment by VitaliKaiser** [comment]
check: Ja hatte ich tatsäclich vergessen :(
Issue schließen?

**Comment by MartinThoma** [comment]
Am besten per commit message :-)

**Comment by MartinThoma** [comment]
I'm currently not too happy with how we cite the image, but I don't know how to do it better.

I've asked on StackExchange for help: http://academia.stackexchange.com/q/54724/4092
